### ISSUE TITLE
Export an option field return the ID instead of the value

### ISSUE THREAD

**Issue by Webroju** [justbetter/magento2-product-grid-export#4]
Thanks for this module! But unfortunately, if I have a dropdown field in the export grid, then the option id is exported instead of the value (which is shown in the product grid). Please look at the attached screenshot.
![value-in-product-grid__id-in-export](https://github.com/justbetter/magento2-product-grid-export/assets/13220558/2101219d-e1cb-4d99-b917-1bd594cb2a90)
Thanks for your efforts.

**Comment by shawnbigpixel** [comment]
@Webroju Were you able to fix the issue you mentioned in above screenshot? 
We also want to get values instead IDs in csv file.

**Comment by Webroju** [comment]
no, my client wants not to invest in this issue.

**Comment by haijerome** [comment]
@shawnbigpixel  @Webroju just fixed this issue and added support for Select / MultiSelect Attributes to export the option labels. check this commit [33498a203e ](https://github.com/justbetter/magento2-product-grid-export/pull/5/commits/33498a203e30055f8ccddad83a8f01eb53aa5bd1). It's a great helpful module BTW 👍

**Comment by shawnbigpixel** [comment]
@haijerome Thanks for the update. How can we get this update via composer?

**Comment by haijerome** [comment]
@shawnbigpixel Hi, it's been merged with the main branch now, where you can pull the changes 👍

**Comment by Webroju** [comment]
@haijerome, Thanks for the fix and the upgrade of the module. I'm pleased, that I can confirm, that it works now great. 
Big thanks for your support!

**Comment by haijerome** [comment]
@Webroju  You are most welcome 😀 and happier to contribute to this much helpful module. Thanks a lot for the confirmation !
